### ISSUE TITLE
Schwingbach database is slow in responding

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#41] opened 2019-06-07 08:12 UTC
Might be caused by low remaining disk space of only 1GB.

**Comment by philippkraft** [comment] 2019-06-12 08:03
Cannot reproduce- database is runniong fine for me. Please provide steps t reproduce the problem. If it does not persist, please close the issue.

**Comment by thouska** [comment] 2019-06-25 11:21
Issue remains, if working in the "Jobs" section of the database. 
Everything else runs nice and smooth.

**Comment by philippkraft** [comment] 2019-10-23 08:56
I guess this is solved by now?

**Closed** 2019-10-24 14:12 UTC
